global using FluentValidation;
global using Fudie.DependencyInjection;
global using Fudie.Domain;
global using Fudie.Firestore.EntityFrameworkCore.Metadata.Builders;
global using Fudie.Infrastructure;
global using Fudie.Validation;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using PlanAgg = Plan.Features.Plans.Domain.PlanAggregate.Plan;
global using Plan.Features.Plans.Domain.PlanAggregate.Enums;
global using Plan.Features.Plans.Domain.PlanAggregate.ValueObjects;
