global using System.Reflection;
global using System.Text.Json.Serialization;
global using FluentValidation;
global using Fudie.DependencyInjection;
global using Fudie.Domain;
global using Fudie.Features;
global using Fudie.Http;
global using Fudie.Infrastructure;
global using Fudie.Validation;
global using Microsoft.AspNetCore.StaticFiles;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.FileProviders;
global using Plan.Features.Plans.Domain.PlanAggregate;
global using Plan.Features.Plans.Domain.PlanAggregate.Enums;
global using Plan.Features.Plans.Domain.PlanAggregate.ValueObjects;
global using Plan.Infrastructure;
global using PlanAgg = Plan.Features.Plans.Domain.PlanAggregate.Plan;

